[database]
dbname = "postgres"
table = "user_metrics_en"
user = "postgres"
password = "postgrespassword"
host = "localhost"
port = 5433

[metrics]
action_type = true
discussion_depth = false
toxicity = true
user_involved = false
vandalism = false
chain = false

[general]
target_field = "username"
buffer_size = 10000000
