[database]
dbname = "postgres"
table = "page_metrics_es"
user = "postgres"
password = "postgrespassword"
host = "localhost"
port = 5433

[metrics]
action_type = true
discussion_depth = true
toxicity = true
user_involved = true
vandalism = true
hindex = true
chain = true

[general]
target_field = "pageTitle"
buffer_size = 1000000