output_device = "json"

[json]
filename = "page_metrics_es"
reset = true

[database]
dbname = "postgres"
table = "page_metrics_es"
user = "postgres"
password = "postgrespassword"
host = "localhost"
port = 5433
reset = true

[metrics]
action_type = true
discussion_depth = true
toxicity = true
user_involved = true
vandalism = true
hindex = true
chain = true

[general]
target_field = "pageId"
buffer_size = 1000000
filter_user_pages = true
