[database]
dbname = "postgres"
table = "page_metrics_it"
user = "postgres"
password = "postgrespassword"
host = "localhost"
port = 5433
reset = true

[metrics]
action_type = false
discussion_depth = false
toxicity = false
user_involved = false
vandalism = false
hindex = false
chain = true

[general]
target_field = "pageTitle"
buffer_size = 500000