output_device = "json"

[json]
filename = "page_metrics_it"
reset = true

[database]
dbname = "postgres"
table = "page_metrics_it"
user = "postgres"
password = "postgrespassword"
host = "localhost"
port = 5433
reset = true

[metrics]
action_type = false
discussion_depth = false
toxicity = false
user_involved = false
vandalism = false
hindex = false
chain = true

[general]
target_field = "pageId"
buffer_size = 500000
filter_user_pages = true
